git cd C:/Users/Weg/Documents/WelfGame
git add -A
git commit -m "Not sure what changed from last time exactly, since I didn't learn how to use this Git Hub thing until now! Well, now there are some more levels to check out, they're also in the main menu, including a stinky fake 3D one that I didn't finish. There are also some new enemies, such as FluffyMac, Cellguy, and MillieHorsie, still in the works. I also broke something somewhere and collision is now janky again."
git push
